<?php
/**
 * Copyright 1999-2017. Parallels IP Holdings GmbH.
 */
?>
<div id="pagespeed">
    <div class="logo">
        <a href="<?php echo pm_Context::getBaseUrl(); ?>" title="PageSpeed Extension">
            <img src="/modules/pagespeed-insights/images/pagespeed-logo.png" alt="PageSpeed Logo"/>
        </a>
    </div>
    <?php echo $this->output_description; ?>
    <?php echo $this->output_description_link; ?>
    <?php echo $this->form; ?>
    <?php echo $this->config; ?>
</div>
